package db

const (
	CreateBlocksTable = `
	CREATE TABLE IF NOT EXISTS blocks (
		hash VARCHAR PRIMARY KEY,
		height BIGINT NOT NULL,
		timestamp TIMESTAMP NOT NULL,
		size INTEGER NOT NULL,
		weight INTEGER NOT NULL,
		tx_count INTEGER NOT NULL,
		previous_block_hash VARCHAR,
		merkle_root VARCHAR NOT NULL,
		nonce INTEGER NOT NULL,
		bits VARCHAR NOT NULL,
		difficulty DOUBLE NOT NULL,
		processed_at TIMESTAMP NOT NULL
	);
	CREATE INDEX IF NOT EXISTS idx_blocks_height ON blocks(height);
	CREATE INDEX IF NOT EXISTS idx_blocks_timestamp ON blocks(timestamp);
	`

	CreateTransactionsTable = `
	CREATE TABLE IF NOT EXISTS transactions (
		txid VARCHAR PRIMARY KEY,
		block_hash VARCHAR NOT NULL,
		block_height BIGINT NOT NULL,
		size INTEGER NOT NULL,
		vsize INTEGER NOT NULL,
		weight INTEGER NOT NULL,
		fee BIGINT NOT NULL,
		input_count INTEGER NOT NULL,
		output_count INTEGER NOT NULL,
		input_value BIGINT NOT NULL,
		output_value BIGINT NOT NULL,
		timestamp TIMESTAMP NOT NULL,
		processed_at TIMESTAMP NOT NULL
	);
	CREATE INDEX IF NOT EXISTS idx_transactions_block_hash ON transactions(block_hash);
	CREATE INDEX IF NOT EXISTS idx_transactions_block_height ON transactions(block_height);
	CREATE INDEX IF NOT EXISTS idx_transactions_timestamp ON transactions(timestamp);
	`

	CreateTxInputsTable = `
	CREATE TABLE IF NOT EXISTS tx_inputs (
		id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		txid VARCHAR NOT NULL,
		vout INTEGER NOT NULL,
		script_sig VARCHAR,
		sequence INTEGER NOT NULL,
		prev_txid VARCHAR,
		prev_vout INTEGER,
		value BIGINT,
		address VARCHAR,
		txid_spending VARCHAR NOT NULL
	);
	CREATE INDEX IF NOT EXISTS idx_tx_inputs_txid ON tx_inputs(txid_spending);
	CREATE INDEX IF NOT EXISTS idx_tx_inputs_prev ON tx_inputs(prev_txid, prev_vout);
	`

	CreateTxOutputsTable = `
	CREATE TABLE IF NOT EXISTS tx_outputs (
		id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		txid VARCHAR NOT NULL,
		vout INTEGER NOT NULL,
		value BIGINT NOT NULL,
		script_pub_key VARCHAR,
		address VARCHAR,
		spent_txid VARCHAR,
		spent_vout INTEGER
	);
	CREATE INDEX IF NOT EXISTS idx_tx_outputs_txid ON tx_outputs(txid);
	CREATE INDEX IF NOT EXISTS idx_tx_outputs_address ON tx_outputs(address);
	CREATE INDEX IF NOT EXISTS idx_tx_outputs_spent ON tx_outputs(spent_txid, spent_vout);
	`

	CreateProcessingStatusTable = `
	CREATE TABLE IF NOT EXISTS processing_status (
		block_height BIGINT PRIMARY KEY,
		block_hash VARCHAR NOT NULL,
		status VARCHAR NOT NULL CHECK (status IN ('processing', 'completed', 'failed')),
		started_at TIMESTAMP NOT NULL,
		completed_at TIMESTAMP,
		error_message VARCHAR
	);
	CREATE INDEX IF NOT EXISTS idx_processing_status_status ON processing_status(status);
	`
)